"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";

export default function DaftarPencariPage() {
  const router = useRouter();
    const [step, setStep] = useState<"form" | "otp">("form");
      const [form, setForm] = useState({ name: "", email: "", phone: "", password: "" });
        const [error, setError] = useState<string | null>(null);
          const [loading, setLoading] = useState(false);
            const [otp, setOtp] = useState("");

              // Kode OTP disimulasikan & ditampilkan langsung di layar untuk keperluan
                // prototipe — di produksi ini dikirim lewat SMS/WhatsApp (lihat dokumen
                  // spesifikasi bagian "Tingkat 0 — Akun dasar").
                    const simulatedOtp = useMemo(() => String(Math.floor(100000 + Math.random() * 900000)), [step]);

                      function update<K extends keyof typeof form>(key: K, value: string) {
                          setForm((f) => ({ ...f, [key]: value }));
                            }

                              function handleContinue(e: React.FormEvent) {
                                  e.preventDefault();
                                      setStep("otp");
                                        }

                                          async function handleVerifyOtp(e: React.FormEvent) {
                                              e.preventDefault();
                                                  setError(null);
                                                      if (otp !== simulatedOtp) {
                                                            setError("Kode OTP tidak sesuai. Periksa kembali kode yang ditampilkan di layar.");
                                                                  return;
                                                                      }
                                                                          setLoading(true);
                                                                              try {
                                                                                    const res = await fetch("/api/auth/register-pencari", {
                                                                                            method: "POST",
                                                                                                    headers: { "Content-Type": "application/json" },
                                                                                                            body: JSON.stringify(form),
                                                                                                                  });
                                                                                                                        const body = await res.json();
                                                                                                                              if (!res.ok) throw new Error(body.error ?? "Pendaftaran gagal");
                                                                                                                                    router.push("/cari");
                                                                                                                                          router.refresh();
                                                                                                                                              } catch (err) {
                                                                                                                                                    setError(err instanceof Error ? err.message : "Terjadi kesalahan");
                                                                                                                                                        } finally {
                                                                                                                                                              setLoading(false);
                                                                                                                                                                  }
                                                                                                                                                                    }
                                                                                                                                                                    
                                                                                                                                                                      return (
                                                                                                                                                                          <main>
                                                                                                                                                                                <div className="max-w-md mx-auto px-6 py-16">
                                                                                                                                                                                        <h1 className="font-display font-bold text-2xl mb-1">Daftar sebagai pencari jasa</h1>
                                                                                                                                                                                                <p className="text-inksoft text-sm mb-7">Verifikasi dasar ini diperlukan supaya mitra juga terlindungi dari akun fiktif.</p>
                                                                                                                                                                                                
                                                                                                                                                                                                        {step === "form" ? (
                                                                                                                                                                                                                  <form onSubmit={handleContinue} className="card p-6 flex flex-col gap-4">
                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                            <label className="block text-xs text-inkfaint mb-1.5 font-medium">Nama lengkap</label>
                                                                                                                                                                                                                                                          <input required value={form.name} onChange={(e) => update("name", e.target.value)} className="w-full border border-border rounded-lg px-3.5 py-2.5 text-sm" />
                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                <label className="block text-xs text-inkfaint mb-1.5 font-medium">Email</label>
                                                                                                                                                                                                                                                                                                              <input required type="email" value={form.email} onChange={(e) => update("email", e.target.value)} className="w-full border border-border rounded-lg px-3.5 py-2.5 text-sm" />
                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                    <label className="block text-xs text-inkfaint mb-1.5 font-medium">Nomor HP</label>
                                                                                                                                                                                                                                                                                                                                                                  <input required placeholder="08xxxxxxxxxx" value={form.phone} onChange={(e) => update("phone", e.target.value)} className="w-full border border-border rounded-lg px-3.5 py-2.5 text-sm" />
                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                        <label className="block text-xs text-inkfaint mb-1.5 font-medium">Kata sandi</label>
                                                                                                                                                                                                                                                                                                                                                                                                                      <input required type="password" minLength={8} value={form.password} onChange={(e) => update("password", e.target.value)} className="w-full border border-border rounded-lg px-3.5 py-2.5 text-sm" />
                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="text-[11px] text-inkfaint mt-1">Minimal 8 karakter, kombinasi huruf & angka.</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button className="bg-accent text-white font-semibold text-sm py-3 rounded-lg">Lanjut verifikasi nomor HP</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <form onSubmit={handleVerifyOtp} className="card p-6 flex flex-col gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="bg-accentsoft border border-[#C9D6F2] rounded-lg p-3.5 text-sm text-accentink">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Kode verifikasi dikirim ke <b>{form.phone}</b>. (Simulasi prototipe — kode: <span className="font-mono font-bold">{simulatedOtp}</span>)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <label className="block text-xs text-inkfaint mb-1.5 font-medium">Kode OTP</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input required value={otp} onChange={(e) => setOtp(e.target.value)} className="w-full border border-border rounded-lg px-3.5 py-2.5 text-sm tracking-widest font-mono" maxLength={6} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {error && <div className="text-sm text-danger">{error}</div>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button disabled={loading} className="bg-accent text-white font-semibold text-sm py-3 rounded-lg disabled:opacity-60">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {loading ? "Memproses…" : "Verifikasi & Buat Akun"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
